routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomepageController; 
use App\Http\Controllers\AdminController; 
use App\Http\Controllers\TarianController; 

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomepageController::class, 'index'])->name('root');
Route::get('/detail/{id}', [HomepageController::class, 'detail'])->name('detail');

Route::view('/tentang', '_partials.tentang')->name('desc');

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');

Route::prefix('admin')->group(function() {

    Route::get('/dashboard', [AdminController::class, 'index'])
        ->name('admin.dashboard')
        ->middleware('auth');
    
    Route::get('/tarian', [TarianController::class, 'index'])
        ->name('tarian')
        ->middleware('auth');
    
    Route::get('/tarian/tambah', [TarianController::class, 'create'])
        ->name('tarian.create')
        ->middleware('auth');
    
    Route::post('/tarian/tambah', [TarianController::class, 'store'])
        ->name('tarian.store')
        ->middleware('auth');
    
    Route::post('/tarian/upload-gambar', [TarianController::class, 'ImageUpload'])
        ->name('tarian.upload.gambar')
        ->middleware('auth');

    Route::get('tarian/{id}/edit', [TarianController:: class, 'edit'])
        ->name('tarian.edit')
        ->middleware('auth');
    
    Route::put('tarian/{id}', [TarianController:: class, 'update'])
        ->name('tarian.update')
        ->middleware('auth');
        
    Route::delete('/tarian/{id}', [TarianController::class, 'destroy'])
        ->name('tarian.delete')
        ->middleware('auth');



});

require __DIR__.'/auth.php';

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/_app.blade.php
<!doctype html>
<html lang="en">
<head>
<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <title>Hello, world!</title>
</head>
<body>

    <div class="container pt-5">
        @yield('content')
    </div>



    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
    -->
</body>
</html>

resources/views/_homepage.blade.php
@extends('_app')

@section('content')
    <h1 class="text-center">List Informasi Tarian</h1>
    <hr>
    @if( count($data) === 0 )
        <h3 class="text-info">Maaf, Belum Ada Data</h3>
    @else
        <!-- <div class="card-group"> -->
        <div class="row row-cols-1 row-cols-lg-4 g-4">  
            @foreach($data as $tarian)
                <div class="col">
                    <div class="card m-2">
                        <div class="card-header">
                            {{ $tarian->nama }} - {{ $tarian->daerah_asal }}
                        </div>
                        <div class="card-body">
                            <h6 class="card-title">Deskripsi</h6>
                            <p class="card-text">
                                {{ Str::limit($tarian->deskripsi, 50) }}
                            </p>
                            <a href="{{ route('detail', $tarian->id) }}" 
                                class="btn btn-primary btn-sm">
                                Detail
                            </a>
                        </div>
                    </div>
                </div>
            @endforeach
        </div>
    @endif
@endsection

resources/views/admin_app.blade.php
@include('_layouts.admin.header')

    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Start Bootstrap</a>
        <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2" />
                <div class="input-group-append">
                    <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
                </div>
            </div>
        </form>
        <div class="navbar-nav ml-auto ml-md-0"></div>
    </nav>

    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading"></div>
                        <a class="nav-link" href="{{ route('admin.dashboard') }}">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Dashboard
                        </a>
                        <div class="sb-sidenav-menu-heading">Menu</div>
                        <a class="nav-link" href="{{ route('tarian') }}">
                            <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                            Tarian
                        </a>
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as: {{Auth::user()->name}}</div>
                    <div class="small">
                        <form method="POST" action="{{ route('logout') }}">
                        @csrf
    
                            <a href="route('logout')"
                                    onclick="event.preventDefault();this.closest('form').submit();">
                                Logout
                            </a>
                        </form>
                    </div>
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid">
                    @yield('title')
                    @yield('breadcrumb')
                    @yield('content')
                </div>
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2021</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
    </div>

    @include('_layouts.admin.footer')
    <!-- @yield('ckeditor') -->
</body>
</html>

resources/views/app.blade.php
@include('_layouts.header')

    <div class="gtco-loader"></div>

    <div id="page">
		<nav class="gtco-nav" role="navigation">
			<div class="container">
				<div class="row">
					<div class="col-xs-2 text-left">
						<div id="gtco-logo"><a href="{{ route('root') }}">Verb<span>.</span></a></div>
					</div>
					<div class="col-xs-10 text-right menu-1">
						<ul>
							<li>
								<a href="{{ route('desc') }}">Tentang</a>
							</li>
							<li>
								<a href="{{ route('login') }}">Login</a>
							</li>
						</ul>
					</div>
				</div>

			</div>
		</nav>

		<header id="gtco-header" class="gtco-cover" role="banner" 
			data-stellar-background-ratio="0.5" style="background-color:#3B3F43">
			<!-- <div class="overlay"></div> -->
			@yield('overlay')
			<div class="container">
				<div class="row">
					<div class="col-md-12 text-left">
						<div class="display-t">
							<div class="display-tc animate-box" data-animate-effect="fadeInUp">
								<h1 class="mb30 text-center">
                                    @if( Route::currentRouteName() == 'detail' )
                                        {{ $data->nama }} - {{ $data->daerah_asal }}
                                    @elseif( Route::currentRouteName() == 'root' )
                                        Seputar Informasi Tarian Indonesia
									@else
										Tentang
                                    @endif
                                </h1>
							</div>
						</div>
					</div>
				</div>
			</div>
		</header>

        @yield('content')

		<footer id="gtco-footer" role="contentinfo">
			<div class="container">
				<div class="row copyright">
					<div class="col-md-12 text-center">
						<p>
							<small class="block">&copy; 2016 Free HTML5. All Rights Reserved.</small>
							<small class="block">Designed by <a href="http://gettemplates.co/"
									target="_blank">GetTemplates.co</a> Demo Images: <a href="http://unsplash.com/"
									target="_blank">Unsplash</a></small>
						</p>
						<p>
						<ul class="gtco-social-icons">
							<li><a href="#"><i class="icon-twitter"></i></a></li>
							<li><a href="#"><i class="icon-facebook"></i></a></li>
							<li><a href="#"><i class="icon-linkedin"></i></a></li>
							<li><a href="#"><i class="icon-dribbble"></i></a></li>
						</ul>
						</p>
					</div>
				</div>

			</div>
		</footer>
	</div>

    <div class="gototop js-top">
		<a href="#" class="js-gotop"><i class="icon-arrow-up"></i></a>
	</div>

@include('_layouts.footer')

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    You're logged in!
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/detail.blade.php
@extends('_app')

@section('content')
    <div class="card">
        @if( !isset($data->img) )
            <svg class="bd-placeholder-img card-img-top" width="100%" height="180" x
                mlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Image cap" preserveAspectRatio="xMidYMid slice" focusable="false">
                <title>Placeholder</title>
                <rect width="100%" height="100%" fill="#868e96"></rect>
                <text x="50%" y="50%" fill="#dee2e6" dy=".3em">Image cap</text>
            </svg>
        @else 
            <img src="#" class="card-img-top" alt="Foto">
        @endif
        <div class="card-body">
            <h5 class="card-title">{{ $data->nama }}</h5>
            <h6 class="card-subtitle mb-2 text-muted">{{ $data->daerah_asal }}</h6>
            <p class="card-text mt-4">{{ $data->deskripsi }}</p>
        </div>
    </div>
@endsection

resources/views/tentang.blade.php
<h1>tes</h1>